fixes:
  - "stripeslack/code::code"
ignore: # Ignoring irrelevant code. Default SS stuff should not be called out by Codecoverage
  - "code/actions"
  - "code/admins"
  - "code/extensions"
  - "code/forms"