# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: brettt89/silverstripe-web
        environment:
          - SS_DATABASE_CLASS=MySQLPDODatabase
          - SS_DATABASE_SERVER=127.0.0.1
          - SS_DATABASE_USERNAME=root
          - SS_DATABASE_PASSWORD=ubuntu
          - SS_DATABASE_NAME=circle_test
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_USER=root
          - MYSQL_ROOT_PASSWORD=ubuntu
          - MYSQL_DATABASE=circle_test
          - MYSQL_HOST=127.0.0.1

    working_directory: ~/var/www

    steps:
      # Install additional requirements

      - run: composer create-project firesphere/stripeslack:ss4-dev -n -s dev ~/var/www
      - run: vendor/silverstripe/framework/sake dev/build

      # run tests!
      - run: vendor/bin/phpunit -d memory_limit=1G --coverage-clover=coverage.xml tests
      - run: bash <(curl -s https://codecov.io/bash) -f coverage.xml
