SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Firesphere\StripeSlack\Extension\SiteConfigExtension
SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - Firesphere\StripeSlack\Extension\ControllerExtension