---
Name: stripeslackroutes
---
SilverStripe\Control\Director:
  rules:
    'SlackAuthorization': Firesphere\StripeSlack\Controller\SlackAuthController
    'SlackStatus//$Action/$ID/$OtherID': Firesphere\StripeSlack\Controller\SlackStatusController
